# Workflow to publish Godot HTML5 games to GitHub Pages

name: 'Build and Publish to GitHub Pages'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: chickensoft-games/setup-godot@v1.5.4
       	with:
	        version: 4.0.2
	        use-dotnet: false

      - name: Create staging directory
        run: mkdir -v -p build/web

      - name: Build
        run: godot -v --export-release "Web" ../build/web/index.html project/project.godot

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'